<h2>Login de usuario</h2>
<form id="form1" name="form1" method="post" action="<?php echo BASE_URL;?>login/validarDatos">
<input type="hidden" name="guardar" value="1" />
<table width="800" border="1">
  <tr>
    <td align="right">Usuario:</td>
    <td>
        <input type="text" name="email" />
        
    </td>
  </tr>
  <tr>
    <td align="right">Contrasena:</td>
    <td>
      <input type="password" name="contrasena"  />
    </td>
  </tr>
  <tr>
    <td colspan="2" align="center">
      <input type="submit" name="button" id="button" value="Acceder" />
    </td>
  </tr>
</table>
 </form>
<br>
 <h2>Registro de nuevo usuario</h2>
 <form id="form1" name="form1" method="post" action="<?php echo BASE_URL;?>registro/validar/">
<input type="hidden" name="guardar" id="hiddenField" value="1" />

<table width="800" border="0" align="center">
  <tr>
    <td align="right">Nombre:</td>
    <td>
      <input type="text" name="nombre" />     </td>
    </tr>
  <tr>
    <td align="right">Apellidos:</td>
    <td><input type="text" name="apellidos" /></td>
    </tr>
  <tr>
    <td align="right">Dirección:</td>
    <td><input type="text" name="direccion"  /></td>
    </tr>
  <tr>
    <td align="right">Email:</td>
    <td>
    <input type="text" name="email" />   </td>
    </tr>
  <tr>
    <td align="right">Teléfono:</td>
    <td><input type="text" name="telefono" /></td>
    </tr>
  <tr>
    <td align="right">Ciudad:</td>
    <td><input type="text" name="ciudad" /></td>
    </tr>
  <tr>
    <td align="right">Pais:</td>
    <td><input type="text" name="pais" /></td>
    </tr>
  <tr>
    <td align="right">Contraseña:</td>
    <td><input type="password" name="contrasena" /></td>
  </tr>
  <tr>
    <td align="right">&nbsp;</td>
    <td>
     <input type="submit" name="button" id="button" value="Registrar" />
    </td>
    </tr>
</table>
</form>
