<h2><?php echo $this->titulo; ?></h2>
<?php include ROOT . DS . "views" . DS . "amistades" . DS . "menu.phtml"; ?>

<?php if(count($this->amigos)){ ?>
<table width="95%">
	<tr>
		<th></th>
		<th>Nombre</th>
		<th>Email</th>
	</tr>

	<?php foreach ($this->amigos as $amigo){?>
	<tr>
		<td><a href="<?php echo BASE_URL . 'amistades/eliminar/' . $amigo['id'];?>">Eliminar</a>
		<td><?php echo $amigo['nombre'];?></td>
		<td><?php echo $amigo['email'];?></td>
	</tr>
	<?php }
	}else echo "<h2>No se encontraron amigos</h2>"; ?>
</table>